// Code generated by protoc-gen-go.
// source: acls.proto
// DO NOT EDIT!

/*
Package apiclient is a generated protocol buffer package.

It is generated from these files:
	acls.proto
	analysis.proto
	anomaly.proto
	api.proto
	artifact.proto
	checks.proto
	config_file.proto
	data_server.proto
	data_store.proto
	export.proto
	flows.proto
	jobs.proto
	knowledge_base.proto
	output_plugin.proto
	semantic.proto
	sysinfo.proto

It has these top-level messages:
	ClientApprovalAuthorization
	Sample
	SampleFloat
	Graph
	GraphFloat
	Event
	Anomaly
	ApiAuthorization
	ApiSearchClientsArgs
	ApiSearchClientsResult
	ApiGetClientArgs
	ApiGetClientResult
	ApiGetClientVersionTimesArgs
	ApiGetClientVersionTimesResult
	ApiInterrogateClientArgs
	ApiInterrogateClientResult
	ApiGetInterrogateOperationStateArgs
	ApiGetInterrogateOperationStateResult
	ApiGetLastClientIPAddressArgs
	ApiGetLastClientIPAddressResult
	ApiGetFlowArgs
	ApiCreateFlowArgs
	ApiCancelFlowArgs
	ApiListFlowResultsArgs
	ApiListFlowResultsResult
	ApiListFlowLogsArgs
	ApiListFlowLogsResult
	ApiGetFlowResultsExportCommandArgs
	ApiGetFlowResultsExportCommandResult
	ApiListFlowOutputPluginsArgs
	ApiListFlowOutputPluginsResult
	ApiListFlowOutputPluginLogsArgs
	ApiListFlowOutputPluginLogsResult
	ApiListFlowOutputPluginErrorsArgs
	ApiListFlowOutputPluginErrorsResult
	ApiGetFlowFilesArchiveArgs
	ApiListFlowDescriptorsArgs
	ApiListFlowDescriptorsResult
	ApiListFlowsArgs
	ApiListFlowsResult
	ApiAddClientsLabelsArgs
	ApiRemoveClientsLabelsArgs
	ApiListClientsLabelsResult
	ApiListKbFieldsResult
	ApiListHuntsArgs
	ApiListHuntsResult
	ApiGetHuntArgs
	ApiGetHuntClientCompletionStatsArgs
	ApiGetHuntClientCompletionStatsResult
	ApiListHuntLogsArgs
	ApiListHuntLogsResult
	ApiListHuntErrorsArgs
	ApiListHuntErrorsResult
	ApiListHuntCrashesArgs
	ApiListHuntCrashesResult
	ApiListHuntResultsArgs
	ApiListHuntResultsResult
	ApiGetHuntResultsExportCommandArgs
	ApiGetHuntResultsExportCommandResult
	ApiListHuntOutputPluginsArgs
	ApiListHuntOutputPluginsResult
	ApiListHuntOutputPluginLogsArgs
	ApiListHuntOutputPluginLogsResult
	ApiListHuntOutputPluginErrorsArgs
	ApiListHuntOutputPluginErrorsResult
	ApiGetHuntFilesArchiveArgs
	ApiGetHuntFileArgs
	ApiGetHuntStatsArgs
	ApiGetHuntStatsResult
	ApiListHuntClientsArgs
	ApiHuntClient
	ApiListHuntClientsResult
	ApiDataObject
	ApiDataObjectKeyValuePair
	ApiGetHuntContextArgs
	ApiGetHuntContextResult
	ApiCreateHuntArgs
	ApiGetRDFValueDescriptorArgs
	ApiListStatsStoreMetricsMetadataArgs
	ApiListCronJobsArgs
	ApiListCronJobsResult
	ApiDeleteCronJobArgs
	ApiGetStatsStoreMetricArgs
	ApiListArtifactsArgs
	ApiListArtifactsResult
	ApiUploadArtifactArgs
	ApiDeleteArtifactsArgs
	ApiGetConfigResult
	ApiGetConfigOptionArgs
	ApiListUserHuntApprovalsArgs
	ApiListUserHuntApprovalsResult
	ApiListUserCronApprovalsArgs
	ApiListUserCronApprovalsResult
	ApiCreateUserClientApprovalArgs
	ApiGetUserClientApprovalArgs
	ApiListUserClientApprovalsArgs
	ApiListUserClientApprovalsResult
	ApiStartRobotGetFilesOperationArgs
	ApiStartRobotGetFilesOperationResult
	ApiGetRobotGetFilesOperationStateArgs
	ApiGetRobotGetFilesOperationStateResult
	ApiAFF4ObjectRendererArgs
	ApiGRRHuntRendererArgs
	ApiRDFValueCollectionRendererArgs
	ApiGrrUserInterfaceTraits
	ApiGrrUser
	ApiConfigOption
	ApiConfigSection
	ApiFlowDescriptor
	ApiUserHuntApproval
	ApiUserCronApproval
	ApiUserClientApproval
	ApiClient
	ApiFlow
	ApiFlowResult
	ApiHunt
	ApiHuntResult
	ApiCronJob
	ApiOutputPlugin
	ApiFile
	ApiGetFileDetailsArgs
	ApiGetFileDetailsResult
	ApiAff4ObjectRepresentation
	ApiAff4ObjectType
	ApiAff4ObjectAttribute
	ApiAff4ObjectAttributeValue
	ApiListFilesArgs
	ApiListFilesResult
	ApiGetFileTextArgs
	ApiGetFileTextResult
	ApiListKnownEncodingsResult
	ApiGetFileBlobArgs
	ApiGetFileVersionTimesArgs
	ApiGetFileVersionTimesResult
	ApiGetFileDownloadCommandArgs
	ApiGetFileDownloadCommandResult
	ApiCreateVfsRefreshOperationArgs
	ApiGetVfsTimelineArgs
	ApiGetVfsTimelineResult
	ApiGetVfsTimelineAsCsvArgs
	ApiVfsTimelineItem
	ApiCreateVfsRefreshOperationResult
	ApiGetVfsRefreshOperationStateArgs
	ApiGetVfsRefreshOperationStateResult
	ApiUpdateVfsFileContentArgs
	ApiUpdateVfsFileContentResult
	ApiGetVfsFileContentUpdateStateArgs
	ApiGetVfsFileContentUpdateStateResult
	ApiGetPendingUserNotificationsCountResult
	ApiDeletePendingUserNotificationArgs
	ApiListAndResetUserNotificationsArgs
	ApiListAndResetUserNotificationsResult
	ApiListPendingUserNotificationsArgs
	ApiListPendingUserNotificationsResult
	ApiNotification
	ApiNotificationReference
	ApiNotificationDiscoveryReference
	ApiNotificationFileDownloadReference
	ApiNotificationArchiveGenerationFinishedReference
	ApiNotificationHuntReference
	ApiNotificationCronReference
	ApiNotificationFlowReference
	ApiNotificationVfsReference
	ApiNotificationFlowStatusReference
	ApiNotificationGrantAccessReference
	ApiListPendingGlobalNotificationsResult
	ApiDeletePendingGlobalNotificationArgs
	ArtifactSource
	Artifact
	ArtifactProcessorDescriptor
	ArtifactDescriptor
	Check
	Method
	Probe
	Filter
	CheckResult
	CheckResults
	Hint
	Target
	LogTarget
	LogConfig
	NfsClient
	NfsExport
	SshdMatchBlock
	SshdConfig
	NtpConfig
	PamConfigEntry
	PamConfig
	SudoersAlias
	SudoersDefault
	SudoersEntry
	SudoersConfig
	DataStoreCommand
	DataServerInterval
	DataServerState
	DataServerInformation
	DataServerMapping
	DataServerClientInformation
	DataServerEncryptedCreds
	DataServerClientCredentials
	DataServerRebalance
	DataServerFileCopy
	DataStoreAuthToken
	DataStoreRegistrationRequest
	TimestampSpec
	DataStoreValue
	DataStoreRequest
	QueryASTNode
	DataStoreQuery
	ResultSet
	DataStoreResponse
	ExportOptions
	ExportedMetadata
	ExportedClient
	ExportedNetworkInterface
	ExportedDNSClientConfiguration
	ExportedFile
	ExportedRegistryKey
	ExportedProcess
	ExportedNetworkConnection
	ExportedAnomaly
	ExportedCheckResult
	ExportedOpenFile
	ExportedFileStoreHash
	ExportedMatch
	ExportedBytes
	ExportedArtifactFilesDownloaderResult
	ExportedRekallProcess
	ExportedRekallWindowsLoadedModule
	ExportedWindowsHandle
	ExportedLinuxSyscallTableEntry
	ExportedRekallLinuxTask
	ExportedRekallLinuxTaskOp
	ExportedRekallLinuxProcOp
	ACLToken
	GUISettings
	FlowRunnerArgs
	HuntRunnerArgs
	SampleHuntArgs
	FlowRequest
	VariableGenericHuntArgs
	GenericHuntArgs
	BareGrepSpec
	CAEnrolerArgs
	DeleteGRRTempFilesArgs
	UninstallArgs
	UpdateConfigurationArgs
	ExecutePythonHackArgs
	ExecuteCommandArgs
	OnlineNotificationArgs
	UpdateClientArgs
	KeepAliveArgs
	TerminateFlowArgs
	LaunchBinaryArgs
	WinUserActivityInvestigationArgs
	ArtifactCollectorFlowArgs
	ArtifactFilesDownloaderFlowArgs
	ArtifactFilesDownloaderResult
	InterrogateArgs
	FingerprintFileArgs
	FingerprintFileResult
	SophosCollectorArgs
	MACTimesArgs
	FileCollectorArgs
	FirefoxHistoryArgs
	CacheGrepArgs
	ListDirectoryArgs
	RecursiveListDirectoryArgs
	FetchBufferForSparseImageArgs
	MakeNewAFF4SparseImageArgs
	UpdateSparseImageChunksArgs
	GrepArgs
	GlobArgs
	SearchFileContentArgs
	FindFilesArgs
	GetFileArgs
	GetMBRArgs
	ChromeHistoryArgs
	ClientActionArgs
	ConsoleDebugFlowArgs
	CreateGenericHuntFlowArgs
	CreateCronJobFlowArgs
	ModifyHuntFlowArgs
	ManageCronJobFlowArgs
	PlistValueFilterArgs
	RunReportFlowArgs
	EnumerateServicesArgs
	ChromePluginsArgs
	RequestApprovalWithReasonFlowArgs
	GrantApprovalWithReasonFlowArgs
	StartHuntFlowArgs
	DeleteHuntFlowArgs
	StopHuntFlowArgs
	CheckHuntAccessFlowArgs
	UpdateVFSFileArgs
	MultiGetFileArgs
	ProcessHuntResultCollectionsCronFlowArgs
	VerifyHuntOutputPluginsCronFlowArgs
	ListProcessesArgs
	ListVADBinariesArgs
	FileFinderModificationTimeCondition
	FileFinderAccessTimeCondition
	FileFinderInodeChangeTimeCondition
	FileFinderSizeCondition
	FileFinderContentsRegexMatchCondition
	FileFinderContentsLiteralMatchCondition
	FileFinderCondition
	FileFinderDownloadActionOptions
	FileFinderAction
	FileFinderArgs
	FileFinderResult
	FileReference
	RegistryFinderCondition
	RegistryFinderArgs
	MemoryCollectorArgs
	CollectArtifactDependenciesArgs
	ArtifactFallbackCollectorArgs
	KnowledgeBaseInitializationArgs
	ExportCollectionFilesAsArchiveArgs
	EndToEndTestFlowArgs
	DiskVolumeInfoArgs
	CheckFlowArgs
	DumpProcessMemoryArgs
	DumpFlashImageArgs
	HttpRequest
	GrrMessage
	MessageList
	SignedMessageList
	CipherProperties
	CipherMetadata
	ClientCommunication
	GrrStatus
	GrrNotification
	ClientCrash
	HuntNotification
	HuntResultNotification
	FlowNotification
	ClientInformation
	Task
	DataBlob
	BlobArray
	PrintStr
	CopyPathToFile
	BufferReference
	RequestState
	Flow
	CpuSeconds
	CpuSample
	IOSample
	ClientStats
	StartupInfo
	ExecuteRequest
	ExecuteResponse
	PathSpec
	ListDirRequest
	StatFSRequest
	StatEntry
	Collection
	WmiRequest
	KeyValue
	Dict
	AttributedDict
	Certificate
	Uname
	FolderInformation
	NetworkAddress
	Interface
	Hash
	AuthenticodeSignedData
	FingerprintTuple
	FingerprintRequest
	FingerprintResponse
	SignedBlob
	SymmetricCipher
	ExecutePythonRequest
	ExecutePythonResponse
	ClientComponentSummary
	ClientComponent
	LoadComponent
	ExecuteBinaryRequest
	ExecuteBinaryResponse
	DriverInstallTemplate
	SendFileRequest
	GrepSpec
	FindSpec
	PlistRequest
	GetClientStatsRequest
	ForemanClientRuleSet
	ForemanClientRule
	ForemanOsClientRule
	ForemanLabelClientRule
	ForemanRegexClientRule
	ForemanIntegerClientRule
	ForemanRuleAction
	ForemanRule
	HuntError
	FlowLog
	ClientResources
	StatsHistogram
	StatsHistogramBin
	RunningStats
	ClientResourcesStats
	Iterator
	IteratedStatResponse
	Notification
	GlobalNotification
	GlobalNotificationSet
	EmbeddedRDFValue
	AFF4ObjectSummary
	AuditEvent
	ClientSummary
	CronJobRunStatus
	MetricFieldDefinition
	MetricMetadata
	StatsStoreMetricsMetadata
	Distribution
	StatsStoreFieldValue
	StatsStoreValue
	AFF4ObjectLabel
	AFF4ObjectLabelsList
	SeekIndex
	SeekIndexPair
	PersistenceFile
	EndToEndTestResult
	EmptyMessage
	NSRLInformation
	PendingFlowTermination
	DumpProcessMemoryRequest
	PwEntry
	Group
	User
	KnowledgeBase
	OutputPluginDescriptor
	OutputPluginBatchProcessingStatus
	OutputPluginVerificationResult
	OutputPluginVerificationResultsList
	EmailOutputPluginArgs
	BigQueryOutputPluginArgs
	CSVOutputPluginArgs
	AnyValue
	SemanticDescriptor
	SemanticMessageDescriptor
	PackageRepository
	ManagementAgent
	PCIDevice
	Process
	NetworkEndpoint
	NetworkConnection
	Filesystem
	MRUFile
	RunKey
	WindowsServiceInformation
	OSXServiceInformation
	LinuxServiceInformation
	SoftwarePackage
	BrowserHistoryItem
	Volume
	WindowsVolume
	UnixVolume
	DiskUsage
	DNSClientConfiguration
	HardwareInfo
	PlistStringDictEntry
	PlistBoolDictEntry
	LaunchdStartCalendarIntervalEntry
	LaunchdKeepAlive
	LaunchdPlist
	CronTabEntry
	CronTabFile
	URI
	WMIActiveScriptEventConsumer
	WMICommandLineEventConsumer
*/
package apiclient

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClientApprovalAuthorization struct {
	Label                     *string  `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
	RequesterMustBeAuthorized *bool    `protobuf:"varint,2,opt,name=requester_must_be_authorized,json=requesterMustBeAuthorized,def=0" json:"requester_must_be_authorized,omitempty"`
	NumApproversRequired      *uint64  `protobuf:"varint,3,opt,name=num_approvers_required,json=numApproversRequired,def=1" json:"num_approvers_required,omitempty"`
	Users                     []string `protobuf:"bytes,4,rep,name=users" json:"users,omitempty"`
	Groups                    []string `protobuf:"bytes,5,rep,name=groups" json:"groups,omitempty"`
	XXX_unrecognized          []byte   `json:"-"`
}

func (m *ClientApprovalAuthorization) Reset()                    { *m = ClientApprovalAuthorization{} }
func (m *ClientApprovalAuthorization) String() string            { return proto.CompactTextString(m) }
func (*ClientApprovalAuthorization) ProtoMessage()               {}
func (*ClientApprovalAuthorization) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_ClientApprovalAuthorization_RequesterMustBeAuthorized bool = false
const Default_ClientApprovalAuthorization_NumApproversRequired uint64 = 1

func (m *ClientApprovalAuthorization) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *ClientApprovalAuthorization) GetRequesterMustBeAuthorized() bool {
	if m != nil && m.RequesterMustBeAuthorized != nil {
		return *m.RequesterMustBeAuthorized
	}
	return Default_ClientApprovalAuthorization_RequesterMustBeAuthorized
}

func (m *ClientApprovalAuthorization) GetNumApproversRequired() uint64 {
	if m != nil && m.NumApproversRequired != nil {
		return *m.NumApproversRequired
	}
	return Default_ClientApprovalAuthorization_NumApproversRequired
}

func (m *ClientApprovalAuthorization) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ClientApprovalAuthorization) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func init() {
	proto.RegisterType((*ClientApprovalAuthorization)(nil), "ClientApprovalAuthorization")
}

func init() { proto.RegisterFile("acls.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 434 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x91, 0xcd, 0x6a, 0xd5, 0x40,
	0x14, 0x80, 0x19, 0xdb, 0x88, 0xcd, 0xc2, 0xc5, 0x20, 0x12, 0x7f, 0x16, 0x07, 0x57, 0x17, 0x29,
	0x01, 0xdd, 0xa8, 0xdd, 0x68, 0xd2, 0x8d, 0x42, 0xab, 0x10, 0x2c, 0xb8, 0x0b, 0x93, 0xe4, 0xa4,
	0x19, 0x98, 0xcc, 0xc4, 0x39, 0x67, 0x2c, 0xd7, 0x77, 0xb0, 0xe0, 0xce, 0x07, 0xf2, 0x45, 0xd4,
	0xd7, 0x70, 0x21, 0x99, 0xe4, 0xde, 0xae, 0x5d, 0x86, 0x93, 0xf9, 0xbe, 0x6f, 0xce, 0xa4, 0xa9,
	0x6a, 0x0d, 0xe5, 0x93, 0x77, 0xec, 0x1e, 0xde, 0x25, 0x1c, 0x95, 0x65, 0xdd, 0x2e, 0xdf, 0x4f,
	0xbe, 0x25, 0xe9, 0xa3, 0x53, 0xa3, 0xd1, 0x72, 0x31, 0x4d, 0xde, 0x7d, 0x51, 0xa6, 0x08, 0x3c,
	0x38, 0xaf, 0xbf, 0x2a, 0xd6, 0xce, 0xca, 0xb7, 0x69, 0x62, 0x54, 0x83, 0x26, 0x13, 0x20, 0x36,
	0x47, 0xe5, 0xf3, 0xdf, 0x7f, 0xff, 0xfc, 0x14, 0xc7, 0xf2, 0xe9, 0x72, 0x06, 0xe2, 0x0c, 0x78,
	0xd0, 0x04, 0x6a, 0x3d, 0x0f, 0xc5, 0xe9, 0xd9, 0xfc, 0x61, 0x34, 0x12, 0xb0, 0xcb, 0xab, 0x05,
	0x20, 0x7f, 0x89, 0xf4, 0xb1, 0xc7, 0xcf, 0x01, 0x89, 0xd1, 0xd7, 0x63, 0x20, 0xae, 0x1b, 0xac,
	0xd5, 0x6a, 0xc3, 0x2e, 0xbb, 0x05, 0x62, 0x73, 0xe7, 0x24, 0xe9, 0x95, 0x21, 0x2c, 0x7f, 0x88,
	0x68, 0xfa, 0x2e, 0xe4, 0xb5, 0x78, 0xd7, 0x03, 0xfb, 0x80, 0xc7, 0x37, 0x8a, 0x3d, 0x07, 0x66,
	0x0e, 0x28, 0x43, 0x0e, 0x1a, 0x04, 0xa3, 0x89, 0xb1, 0x03, 0x6d, 0x81, 0x07, 0x9c, 0x3b, 0x72,
	0xf8, 0x18, 0xd3, 0x8c, 0x71, 0x57, 0x04, 0x5b, 0x17, 0x80, 0x1d, 0xd0, 0x84, 0xad, 0xee, 0xb7,
	0x30, 0xaa, 0x76, 0xd0, 0x76, 0x8e, 0x1c, 0x14, 0x43, 0xab, 0x2c, 0x38, 0x6b, 0xb6, 0x33, 0x47,
	0xb5, 0x2d, 0x12, 0x61, 0x07, 0xcd, 0x36, 0x92, 0x56, 0x6e, 0x20, 0xf4, 0x94, 0x57, 0x0f, 0xf6,
	0xf6, 0xf3, 0x40, 0x5c, 0x62, 0xb1, 0xbf, 0x82, 0xbc, 0x16, 0xe9, 0x7d, 0x1b, 0xc6, 0x7a, 0x09,
	0x45, 0x4f, 0xf5, 0xfc, 0xaf, 0xf6, 0xd8, 0x65, 0x07, 0x20, 0x36, 0x87, 0x27, 0xe2, 0x59, 0x79,
	0x11, 0x2f, 0xf6, 0x41, 0x9e, 0xbf, 0x0f, 0x63, 0x83, 0x1e, 0x5c, 0x0f, 0x13, 0xba, 0xc9, 0x20,
	0xf4, 0xde, 0x8d, 0xcb, 0x2e, 0xe7, 0x15, 0xc6, 0x2a, 0x8b, 0xd8, 0xcd, 0xcd, 0x2b, 0x10, 0x1a,
	0xec, 0x9d, 0xdf, 0x05, 0x82, 0x26, 0xb8, 0xf4, 0xca, 0x32, 0x76, 0x79, 0x75, 0xcf, 0x86, 0xb1,
	0xd8, 0x69, 0xab, 0xd5, 0x2a, 0x2f, 0xd2, 0x24, 0x56, 0x67, 0x87, 0x70, 0xb0, 0x39, 0x2a, 0x5f,
	0x47, 0xf7, 0x2b, 0xf9, 0xe2, 0x4c, 0x13, 0xcf, 0xe6, 0x38, 0xbc, 0x59, 0xc0, 0x4e, 0xd3, 0xc6,
	0xd7, 0x25, 0xb8, 0xd2, 0x3c, 0x2c, 0x45, 0xf1, 0x0d, 0xf3, 0x6a, 0xa1, 0xc9, 0x4f, 0xe9, 0xed,
	0x4b, 0xef, 0xc2, 0x44, 0x59, 0x12, 0xb9, 0x6f, 0x22, 0xf7, 0x44, 0xbe, 0xdc, 0x71, 0x97, 0xe9,
	0x7f, 0x80, 0x57, 0xde, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7a, 0xaa, 0x5c, 0xdf, 0xac, 0x02,
	0x00, 0x00,
}
