// This file has been autogenerated by ./generate/gen-functions.sh

package apiclient

func (c APIClient) AddClientsLabels(rq ApiAddClientsLabelsArgs) error {
	return c.post("/api/clients/labels/add", &rq)
}
