// Code generated by protoc-gen-go.
// source: analysis.proto
// DO NOT EDIT!

package apiclient

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// A graph is a way to represent data.
type Sample struct {
	Label            *string `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
	XValue           *uint64 `protobuf:"varint,2,opt,name=x_value" json:"x_value,omitempty"`
	YValue           *uint64 `protobuf:"varint,3,opt,name=y_value" json:"y_value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Sample) Reset()                    { *m = Sample{} }
func (m *Sample) String() string            { return proto.CompactTextString(m) }
func (*Sample) ProtoMessage()               {}
func (*Sample) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Sample) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *Sample) GetXValue() uint64 {
	if m != nil && m.XValue != nil {
		return *m.XValue
	}
	return 0
}

func (m *Sample) GetYValue() uint64 {
	if m != nil && m.YValue != nil {
		return *m.YValue
	}
	return 0
}

type SampleFloat struct {
	Label            *string  `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
	XValue           *float32 `protobuf:"fixed32,2,opt,name=x_value" json:"x_value,omitempty"`
	YValue           *float32 `protobuf:"fixed32,3,opt,name=y_value" json:"y_value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *SampleFloat) Reset()                    { *m = SampleFloat{} }
func (m *SampleFloat) String() string            { return proto.CompactTextString(m) }
func (*SampleFloat) ProtoMessage()               {}
func (*SampleFloat) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *SampleFloat) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *SampleFloat) GetXValue() float32 {
	if m != nil && m.XValue != nil {
		return *m.XValue
	}
	return 0
}

func (m *SampleFloat) GetYValue() float32 {
	if m != nil && m.YValue != nil {
		return *m.YValue
	}
	return 0
}

type Graph struct {
	Title            *string   `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Xtitle           *string   `protobuf:"bytes,2,opt,name=xtitle" json:"xtitle,omitempty"`
	Ytitle           *string   `protobuf:"bytes,3,opt,name=ytitle" json:"ytitle,omitempty"`
	Data             []*Sample `protobuf:"bytes,4,rep,name=data" json:"data,omitempty"`
	XScale           *uint32   `protobuf:"varint,5,opt,name=x_scale,def=1" json:"x_scale,omitempty"`
	YScale           *uint32   `protobuf:"varint,6,opt,name=y_scale,def=1" json:"y_scale,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Graph) Reset()                    { *m = Graph{} }
func (m *Graph) String() string            { return proto.CompactTextString(m) }
func (*Graph) ProtoMessage()               {}
func (*Graph) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

const Default_Graph_XScale uint32 = 1
const Default_Graph_YScale uint32 = 1

func (m *Graph) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Graph) GetXtitle() string {
	if m != nil && m.Xtitle != nil {
		return *m.Xtitle
	}
	return ""
}

func (m *Graph) GetYtitle() string {
	if m != nil && m.Ytitle != nil {
		return *m.Ytitle
	}
	return ""
}

func (m *Graph) GetData() []*Sample {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Graph) GetXScale() uint32 {
	if m != nil && m.XScale != nil {
		return *m.XScale
	}
	return Default_Graph_XScale
}

func (m *Graph) GetYScale() uint32 {
	if m != nil && m.YScale != nil {
		return *m.YScale
	}
	return Default_Graph_YScale
}

type GraphFloat struct {
	Title            *string        `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Xtitle           *string        `protobuf:"bytes,2,opt,name=xtitle" json:"xtitle,omitempty"`
	Ytitle           *string        `protobuf:"bytes,3,opt,name=ytitle" json:"ytitle,omitempty"`
	Data             []*SampleFloat `protobuf:"bytes,4,rep,name=data" json:"data,omitempty"`
	XScale           *uint32        `protobuf:"varint,5,opt,name=x_scale,def=1" json:"x_scale,omitempty"`
	YScale           *uint32        `protobuf:"varint,6,opt,name=y_scale,def=1" json:"y_scale,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *GraphFloat) Reset()                    { *m = GraphFloat{} }
func (m *GraphFloat) String() string            { return proto.CompactTextString(m) }
func (*GraphFloat) ProtoMessage()               {}
func (*GraphFloat) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

const Default_GraphFloat_XScale uint32 = 1
const Default_GraphFloat_YScale uint32 = 1

func (m *GraphFloat) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *GraphFloat) GetXtitle() string {
	if m != nil && m.Xtitle != nil {
		return *m.Xtitle
	}
	return ""
}

func (m *GraphFloat) GetYtitle() string {
	if m != nil && m.Ytitle != nil {
		return *m.Ytitle
	}
	return ""
}

func (m *GraphFloat) GetData() []*SampleFloat {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GraphFloat) GetXScale() uint32 {
	if m != nil && m.XScale != nil {
		return *m.XScale
	}
	return Default_GraphFloat_XScale
}

func (m *GraphFloat) GetYScale() uint32 {
	if m != nil && m.YScale != nil {
		return *m.YScale
	}
	return Default_GraphFloat_YScale
}

// The following relate to the timelining functionality.
type Event struct {
	Timestamp *uint64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Source    *string `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	// The name of the object which this event is talking about.
	Subject *string `protobuf:"bytes,3,opt,name=subject" json:"subject,omitempty"`
	// The type of this event.
	Type *string    `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	Stat *StatEntry `protobuf:"bytes,5,opt,name=stat" json:"stat,omitempty"`
	// The sequential number of this event as stored in the time series.
	Id               *uint32 `protobuf:"varint,6,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *Event) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Event) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *Event) GetSubject() string {
	if m != nil && m.Subject != nil {
		return *m.Subject
	}
	return ""
}

func (m *Event) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Event) GetStat() *StatEntry {
	if m != nil {
		return m.Stat
	}
	return nil
}

func (m *Event) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Sample)(nil), "Sample")
	proto.RegisterType((*SampleFloat)(nil), "SampleFloat")
	proto.RegisterType((*Graph)(nil), "Graph")
	proto.RegisterType((*GraphFloat)(nil), "GraphFloat")
	proto.RegisterType((*Event)(nil), "Event")
}

func init() { proto.RegisterFile("analysis.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x91, 0xcf, 0xce, 0x93, 0x40,
	0x14, 0xc5, 0x03, 0x05, 0xbe, 0x7c, 0x97, 0xaf, 0x35, 0x99, 0x68, 0x42, 0xba, 0x9a, 0xe0, 0x06,
	0x37, 0x24, 0xed, 0xce, 0x3f, 0x31, 0xb1, 0x69, 0xeb, 0xce, 0xc4, 0x56, 0xd7, 0xe6, 0x96, 0x4e,
	0xcb, 0x34, 0x03, 0x43, 0x98, 0x4b, 0x53, 0x56, 0xbe, 0x9c, 0xaf, 0xe1, 0x46, 0x5f, 0xc3, 0x85,
	0x19, 0xa0, 0x8d, 0xba, 0x51, 0x77, 0x9c, 0x73, 0xf9, 0xcd, 0x39, 0x77, 0x06, 0x26, 0x58, 0xa2,
	0x6a, 0x8d, 0x34, 0x69, 0x55, 0x6b, 0xd2, 0x53, 0x38, 0xe9, 0xdd, 0xf5, 0x7b, 0x62, 0x44, 0x81,
	0x25, 0xc9, 0xac, 0xd7, 0xf1, 0x73, 0x08, 0xb6, 0x58, 0x54, 0x4a, 0xb0, 0x31, 0xf8, 0x0a, 0x77,
	0x42, 0x45, 0x0e, 0x77, 0x92, 0x7b, 0xf6, 0x08, 0xee, 0x2e, 0x9f, 0xce, 0xa8, 0x1a, 0x11, 0xb9,
	0xdc, 0x49, 0x3c, 0x6b, 0xb4, 0x83, 0x31, 0xb2, 0x46, 0xfc, 0x1a, 0xc2, 0x1e, 0x5d, 0x2b, 0x8d,
	0xf4, 0x17, 0xde, 0xfd, 0x93, 0x77, 0xe3, 0x06, 0xfc, 0xb7, 0x35, 0x56, 0xb9, 0x25, 0x49, 0x92,
	0x12, 0x03, 0x39, 0x81, 0xe0, 0xd2, 0x6b, 0xf7, 0xaa, 0xdb, 0x5e, 0x8f, 0x3a, 0xfd, 0x04, 0xbc,
	0x3d, 0x12, 0x46, 0x1e, 0x1f, 0x25, 0xe1, 0xfc, 0x2e, 0x1d, 0xfa, 0x33, 0x1b, 0x68, 0x32, 0x54,
	0x22, 0xf2, 0xb9, 0x93, 0x8c, 0x5f, 0x38, 0x33, 0xeb, 0xb5, 0x83, 0x17, 0x0c, 0x5e, 0xfc, 0x19,
	0xa0, 0x8b, 0xbd, 0xb5, 0xfe, 0x9f, 0xec, 0xe9, 0x6f, 0xd9, 0x0f, 0xe9, 0xaf, 0x17, 0xf0, 0xaf,
	0x05, 0xbe, 0x3a, 0xe0, 0xaf, 0xce, 0xa2, 0x24, 0xf6, 0x0a, 0xee, 0x49, 0x16, 0xc2, 0x10, 0x16,
	0x55, 0x57, 0xc0, 0x5b, 0x3c, 0xfb, 0xf6, 0xe3, 0xfb, 0x17, 0xe7, 0x29, 0x84, 0x9b, 0xe5, 0x7a,
	0x89, 0x24, 0xec, 0x9c, 0x3d, 0xfe, 0x90, 0x0b, 0x2e, 0x2c, 0xc2, 0x6f, 0xff, 0xa7, 0xec, 0x3d,
	0x04, 0x46, 0x37, 0x75, 0x36, 0x74, 0x5d, 0xbc, 0xe9, 0xd0, 0x97, 0x10, 0x6c, 0x96, 0xeb, 0x8f,
	0x9b, 0x77, 0x6c, 0x66, 0xa9, 0xa6, 0x2e, 0xb9, 0x3e, 0x70, 0xca, 0x05, 0xd7, 0xb5, 0x3c, 0xca,
	0x12, 0x49, 0x96, 0x47, 0xae, 0x77, 0x27, 0x91, 0x11, 0x3f, 0xe8, 0x9a, 0x53, 0x2e, 0x4d, 0x7f,
	0x78, 0x6a, 0xdf, 0xc8, 0x34, 0xdd, 0x68, 0xd8, 0xf7, 0x01, 0x3c, 0x6a, 0x2b, 0x11, 0x79, 0x9d,
	0x8a, 0xc0, 0x33, 0x84, 0xd4, 0xad, 0x17, 0xce, 0x21, 0xdd, 0x12, 0xd2, 0xaa, 0xa4, 0xba, 0x65,
	0x00, 0xae, 0xdc, 0xf7, 0x2b, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x76, 0x29, 0x75, 0x7f,
	0x02, 0x00, 0x00,
}
