// This file has been autogenerated by ./generate/gen-functions.sh

package apiclient

func (c APIClient) ListClientsLabels() (rs *ApiListClientsLabelsResult, err error) {
	rs = new(ApiListClientsLabelsResult)
	if err := c.get("/api/clients/labels", nil, rs); err != nil {
		return nil, err
	}
	return
}
