// This file has been autogenerated by ./generate/gen-functions.sh

package apiclient

func (c APIClient) ListArtifacts(rq ApiListArtifactsArgs) (rs *ApiListArtifactsResult, err error) {
	rs = new(ApiListArtifactsResult)
	if err := c.do("GET", "/api/artifacts", &rq, rs); err != nil {
		return nil, err
	}
	return
}
