// Code generated by protoc-gen-go.
// source: output_plugin.proto
// DO NOT EDIT!

package apiclient

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type OutputPluginBatchProcessingStatus_Status int32

const (
	OutputPluginBatchProcessingStatus_SUCCESS OutputPluginBatchProcessingStatus_Status = 0
	OutputPluginBatchProcessingStatus_ERROR   OutputPluginBatchProcessingStatus_Status = 1
)

var OutputPluginBatchProcessingStatus_Status_name = map[int32]string{
	0: "SUCCESS",
	1: "ERROR",
}
var OutputPluginBatchProcessingStatus_Status_value = map[string]int32{
	"SUCCESS": 0,
	"ERROR":   1,
}

func (x OutputPluginBatchProcessingStatus_Status) Enum() *OutputPluginBatchProcessingStatus_Status {
	p := new(OutputPluginBatchProcessingStatus_Status)
	*p = x
	return p
}
func (x OutputPluginBatchProcessingStatus_Status) String() string {
	return proto.EnumName(OutputPluginBatchProcessingStatus_Status_name, int32(x))
}
func (x *OutputPluginBatchProcessingStatus_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OutputPluginBatchProcessingStatus_Status_value, data, "OutputPluginBatchProcessingStatus_Status")
	if err != nil {
		return err
	}
	*x = OutputPluginBatchProcessingStatus_Status(value)
	return nil
}
func (OutputPluginBatchProcessingStatus_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor13, []int{1, 0}
}

type OutputPluginVerificationResult_Status int32

const (
	OutputPluginVerificationResult_N_A     OutputPluginVerificationResult_Status = 0
	OutputPluginVerificationResult_SUCCESS OutputPluginVerificationResult_Status = 1
	OutputPluginVerificationResult_WARNING OutputPluginVerificationResult_Status = 2
	OutputPluginVerificationResult_FAILURE OutputPluginVerificationResult_Status = 3
)

var OutputPluginVerificationResult_Status_name = map[int32]string{
	0: "N_A",
	1: "SUCCESS",
	2: "WARNING",
	3: "FAILURE",
}
var OutputPluginVerificationResult_Status_value = map[string]int32{
	"N_A":     0,
	"SUCCESS": 1,
	"WARNING": 2,
	"FAILURE": 3,
}

func (x OutputPluginVerificationResult_Status) Enum() *OutputPluginVerificationResult_Status {
	p := new(OutputPluginVerificationResult_Status)
	*p = x
	return p
}
func (x OutputPluginVerificationResult_Status) String() string {
	return proto.EnumName(OutputPluginVerificationResult_Status_name, int32(x))
}
func (x *OutputPluginVerificationResult_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OutputPluginVerificationResult_Status_value, data, "OutputPluginVerificationResult_Status")
	if err != nil {
		return err
	}
	*x = OutputPluginVerificationResult_Status(value)
	return nil
}
func (OutputPluginVerificationResult_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor13, []int{2, 0}
}

type OutputPluginDescriptor struct {
	PluginName       *string `protobuf:"bytes,1,opt,name=plugin_name" json:"plugin_name,omitempty"`
	PluginArgs       []byte  `protobuf:"bytes,2,opt,name=plugin_args" json:"plugin_args,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *OutputPluginDescriptor) Reset()                    { *m = OutputPluginDescriptor{} }
func (m *OutputPluginDescriptor) String() string            { return proto.CompactTextString(m) }
func (*OutputPluginDescriptor) ProtoMessage()               {}
func (*OutputPluginDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{0} }

func (m *OutputPluginDescriptor) GetPluginName() string {
	if m != nil && m.PluginName != nil {
		return *m.PluginName
	}
	return ""
}

func (m *OutputPluginDescriptor) GetPluginArgs() []byte {
	if m != nil {
		return m.PluginArgs
	}
	return nil
}

// Next id: 7
type OutputPluginBatchProcessingStatus struct {
	Status           *OutputPluginBatchProcessingStatus_Status `protobuf:"varint,1,opt,name=status,enum=OutputPluginBatchProcessingStatus_Status,def=0" json:"status,omitempty"`
	PluginDescriptor *OutputPluginDescriptor                   `protobuf:"bytes,6,opt,name=plugin_descriptor" json:"plugin_descriptor,omitempty"`
	Summary          *string                                   `protobuf:"bytes,3,opt,name=summary" json:"summary,omitempty"`
	BatchIndex       *uint64                                   `protobuf:"varint,4,opt,name=batch_index" json:"batch_index,omitempty"`
	BatchSize        *uint64                                   `protobuf:"varint,5,opt,name=batch_size" json:"batch_size,omitempty"`
	XXX_unrecognized []byte                                    `json:"-"`
}

func (m *OutputPluginBatchProcessingStatus) Reset()         { *m = OutputPluginBatchProcessingStatus{} }
func (m *OutputPluginBatchProcessingStatus) String() string { return proto.CompactTextString(m) }
func (*OutputPluginBatchProcessingStatus) ProtoMessage()    {}
func (*OutputPluginBatchProcessingStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{1}
}

const Default_OutputPluginBatchProcessingStatus_Status OutputPluginBatchProcessingStatus_Status = OutputPluginBatchProcessingStatus_SUCCESS

func (m *OutputPluginBatchProcessingStatus) GetStatus() OutputPluginBatchProcessingStatus_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Default_OutputPluginBatchProcessingStatus_Status
}

func (m *OutputPluginBatchProcessingStatus) GetPluginDescriptor() *OutputPluginDescriptor {
	if m != nil {
		return m.PluginDescriptor
	}
	return nil
}

func (m *OutputPluginBatchProcessingStatus) GetSummary() string {
	if m != nil && m.Summary != nil {
		return *m.Summary
	}
	return ""
}

func (m *OutputPluginBatchProcessingStatus) GetBatchIndex() uint64 {
	if m != nil && m.BatchIndex != nil {
		return *m.BatchIndex
	}
	return 0
}

func (m *OutputPluginBatchProcessingStatus) GetBatchSize() uint64 {
	if m != nil && m.BatchSize != nil {
		return *m.BatchSize
	}
	return 0
}

type OutputPluginVerificationResult struct {
	PluginId         *string                                `protobuf:"bytes,1,opt,name=plugin_id" json:"plugin_id,omitempty"`
	PluginDescriptor *OutputPluginDescriptor                `protobuf:"bytes,2,opt,name=plugin_descriptor" json:"plugin_descriptor,omitempty"`
	Status           *OutputPluginVerificationResult_Status `protobuf:"varint,3,opt,name=status,enum=OutputPluginVerificationResult_Status" json:"status,omitempty"`
	StatusMessage    *string                                `protobuf:"bytes,4,opt,name=status_message" json:"status_message,omitempty"`
	Timestamp        *uint64                                `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (m *OutputPluginVerificationResult) Reset()                    { *m = OutputPluginVerificationResult{} }
func (m *OutputPluginVerificationResult) String() string            { return proto.CompactTextString(m) }
func (*OutputPluginVerificationResult) ProtoMessage()               {}
func (*OutputPluginVerificationResult) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{2} }

func (m *OutputPluginVerificationResult) GetPluginId() string {
	if m != nil && m.PluginId != nil {
		return *m.PluginId
	}
	return ""
}

func (m *OutputPluginVerificationResult) GetPluginDescriptor() *OutputPluginDescriptor {
	if m != nil {
		return m.PluginDescriptor
	}
	return nil
}

func (m *OutputPluginVerificationResult) GetStatus() OutputPluginVerificationResult_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return OutputPluginVerificationResult_N_A
}

func (m *OutputPluginVerificationResult) GetStatusMessage() string {
	if m != nil && m.StatusMessage != nil {
		return *m.StatusMessage
	}
	return ""
}

func (m *OutputPluginVerificationResult) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type OutputPluginVerificationResultsList struct {
	Results          []*OutputPluginVerificationResult `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *OutputPluginVerificationResultsList) Reset()         { *m = OutputPluginVerificationResultsList{} }
func (m *OutputPluginVerificationResultsList) String() string { return proto.CompactTextString(m) }
func (*OutputPluginVerificationResultsList) ProtoMessage()    {}
func (*OutputPluginVerificationResultsList) Descriptor() ([]byte, []int) {
	return fileDescriptor13, []int{3}
}

func (m *OutputPluginVerificationResultsList) GetResults() []*OutputPluginVerificationResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type EmailOutputPluginArgs struct {
	EmailAddress     *string `protobuf:"bytes,1,opt,name=email_address" json:"email_address,omitempty"`
	EmailsLimit      *uint64 `protobuf:"varint,2,opt,name=emails_limit,def=100" json:"emails_limit,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EmailOutputPluginArgs) Reset()                    { *m = EmailOutputPluginArgs{} }
func (m *EmailOutputPluginArgs) String() string            { return proto.CompactTextString(m) }
func (*EmailOutputPluginArgs) ProtoMessage()               {}
func (*EmailOutputPluginArgs) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{4} }

const Default_EmailOutputPluginArgs_EmailsLimit uint64 = 100

func (m *EmailOutputPluginArgs) GetEmailAddress() string {
	if m != nil && m.EmailAddress != nil {
		return *m.EmailAddress
	}
	return ""
}

func (m *EmailOutputPluginArgs) GetEmailsLimit() uint64 {
	if m != nil && m.EmailsLimit != nil {
		return *m.EmailsLimit
	}
	return Default_EmailOutputPluginArgs_EmailsLimit
}

type BigQueryOutputPluginArgs struct {
	ExportOptions    *ExportOptions `protobuf:"bytes,2,opt,name=export_options" json:"export_options,omitempty"`
	ConvertValues    *bool          `protobuf:"varint,3,opt,name=convert_values,def=1" json:"convert_values,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *BigQueryOutputPluginArgs) Reset()                    { *m = BigQueryOutputPluginArgs{} }
func (m *BigQueryOutputPluginArgs) String() string            { return proto.CompactTextString(m) }
func (*BigQueryOutputPluginArgs) ProtoMessage()               {}
func (*BigQueryOutputPluginArgs) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{5} }

const Default_BigQueryOutputPluginArgs_ConvertValues bool = true

func (m *BigQueryOutputPluginArgs) GetExportOptions() *ExportOptions {
	if m != nil {
		return m.ExportOptions
	}
	return nil
}

func (m *BigQueryOutputPluginArgs) GetConvertValues() bool {
	if m != nil && m.ConvertValues != nil {
		return *m.ConvertValues
	}
	return Default_BigQueryOutputPluginArgs_ConvertValues
}

type CSVOutputPluginArgs struct {
	ExportOptions    *ExportOptions `protobuf:"bytes,2,opt,name=export_options" json:"export_options,omitempty"`
	ConvertValues    *bool          `protobuf:"varint,3,opt,name=convert_values,def=1" json:"convert_values,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *CSVOutputPluginArgs) Reset()                    { *m = CSVOutputPluginArgs{} }
func (m *CSVOutputPluginArgs) String() string            { return proto.CompactTextString(m) }
func (*CSVOutputPluginArgs) ProtoMessage()               {}
func (*CSVOutputPluginArgs) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{6} }

const Default_CSVOutputPluginArgs_ConvertValues bool = true

func (m *CSVOutputPluginArgs) GetExportOptions() *ExportOptions {
	if m != nil {
		return m.ExportOptions
	}
	return nil
}

func (m *CSVOutputPluginArgs) GetConvertValues() bool {
	if m != nil && m.ConvertValues != nil {
		return *m.ConvertValues
	}
	return Default_CSVOutputPluginArgs_ConvertValues
}

func init() {
	proto.RegisterType((*OutputPluginDescriptor)(nil), "OutputPluginDescriptor")
	proto.RegisterType((*OutputPluginBatchProcessingStatus)(nil), "OutputPluginBatchProcessingStatus")
	proto.RegisterType((*OutputPluginVerificationResult)(nil), "OutputPluginVerificationResult")
	proto.RegisterType((*OutputPluginVerificationResultsList)(nil), "OutputPluginVerificationResultsList")
	proto.RegisterType((*EmailOutputPluginArgs)(nil), "EmailOutputPluginArgs")
	proto.RegisterType((*BigQueryOutputPluginArgs)(nil), "BigQueryOutputPluginArgs")
	proto.RegisterType((*CSVOutputPluginArgs)(nil), "CSVOutputPluginArgs")
	proto.RegisterEnum("OutputPluginBatchProcessingStatus_Status", OutputPluginBatchProcessingStatus_Status_name, OutputPluginBatchProcessingStatus_Status_value)
	proto.RegisterEnum("OutputPluginVerificationResult_Status", OutputPluginVerificationResult_Status_name, OutputPluginVerificationResult_Status_value)
}

func init() { proto.RegisterFile("output_plugin.proto", fileDescriptor13) }

var fileDescriptor13 = []byte{
	// 871 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xd4, 0x54, 0x4f, 0x73, 0xdb, 0x44,
	0x14, 0xaf, 0xe2, 0xb4, 0xc1, 0xeb, 0x60, 0xcc, 0x66, 0x68, 0x55, 0x0e, 0x65, 0x51, 0x21, 0x75,
	0xa1, 0x15, 0x26, 0x9d, 0x16, 0x26, 0x05, 0x32, 0x56, 0xec, 0x74, 0x32, 0x13, 0x9c, 0x62, 0xa7,
	0xcd, 0x81, 0x83, 0x66, 0x2d, 0x3d, 0xdb, 0x5b, 0xa4, 0x95, 0x66, 0x77, 0x55, 0xe2, 0xde, 0xf9,
	0x0c, 0x7c, 0x04, 0x3e, 0x01, 0x17, 0xce, 0x7c, 0x0d, 0x2e, 0x70, 0xe2, 0x3b, 0x70, 0x60, 0xf6,
	0x8f, 0x9d, 0xd0, 0x64, 0xd2, 0x33, 0x27, 0x69, 0x9f, 0xde, 0xef, 0xbd, 0xdf, 0xef, 0xfd, 0x9e,
	0x16, 0x6d, 0x14, 0x95, 0x2a, 0x2b, 0x15, 0x97, 0x59, 0x35, 0x65, 0x3c, 0x2c, 0x45, 0xa1, 0x8a,
	0xf7, 0xd7, 0xe1, 0xa4, 0x2c, 0x84, 0x72, 0xa7, 0xa6, 0x84, 0x9c, 0x72, 0xc5, 0x12, 0x7b, 0x0e,
	0xfe, 0xf0, 0xd0, 0xf5, 0x43, 0x83, 0x7a, 0x6a, 0x40, 0x3d, 0x90, 0x89, 0x60, 0xa5, 0x2a, 0x04,
	0x7e, 0x8c, 0x1a, 0xb6, 0x50, 0xcc, 0x69, 0x0e, 0xbe, 0x47, 0xbc, 0x76, 0x3d, 0xda, 0xfc, 0xf3,
	0x9f, 0xbf, 0x7e, 0xf7, 0x08, 0xbe, 0x75, 0x34, 0x03, 0xa2, 0xe3, 0xa4, 0x98, 0x10, 0x35, 0x03,
	0x62, 0x5b, 0x13, 0xd7, 0x1a, 0xff, 0xe4, 0x2d, 0xd1, 0x54, 0x4c, 0xa5, 0xbf, 0x42, 0xbc, 0xf6,
	0x7a, 0x54, 0x1a, 0xf4, 0x0b, 0x7c, 0xa4, 0xd1, 0x25, 0x15, 0x34, 0x07, 0x05, 0x42, 0x92, 0x49,
	0x21, 0x88, 0x9a, 0x31, 0xb9, 0x80, 0x93, 0x6f, 0x2b, 0xa9, 0xc8, 0x18, 0x08, 0xe5, 0x84, 0x71,
	0xa9, 0x28, 0x4f, 0x96, 0x8d, 0x74, 0xd3, 0xd4, 0x25, 0xde, 0x91, 0x44, 0x57, 0x8f, 0xd5, 0xbc,
	0x84, 0xf0, 0x13, 0xfc, 0x04, 0x9c, 0x8a, 0xae, 0x98, 0xca, 0xdd, 0x8c, 0x4a, 0x19, 0xfc, 0x5d,
	0x43, 0x1f, 0x9e, 0xd5, 0x17, 0x51, 0x95, 0xcc, 0x9e, 0x8a, 0x22, 0x01, 0x29, 0x19, 0x9f, 0x8e,
	0x14, 0x55, 0x95, 0xc4, 0x73, 0x74, 0x4d, 0x9a, 0x37, 0xa3, 0xb2, 0xb9, 0x75, 0x37, 0x7c, 0x23,
	0x26, 0xb4, 0x8f, 0xed, 0xb5, 0xd1, 0xb3, 0xdd, 0xdd, 0xfe, 0x68, 0x14, 0x3d, 0x34, 0xda, 0x3e,
	0xc3, 0xf7, 0x8f, 0xa9, 0xb4, 0x62, 0xc6, 0x1a, 0x47, 0x64, 0x95, 0x68, 0xe0, 0xa4, 0xca, 0xb2,
	0x39, 0x29, 0x6d, 0x15, 0x48, 0x49, 0x21, 0x08, 0x2f, 0xd4, 0x0e, 0x3e, 0x41, 0xef, 0xba, 0x39,
	0xa5, 0xcb, 0xd1, 0xfb, 0xd7, 0x88, 0xd7, 0x6e, 0x6c, 0xdd, 0x08, 0x2f, 0x76, 0x26, 0xea, 0x99,
	0x56, 0xdf, 0xe0, 0xaf, 0x4e, 0x63, 0x17, 0xda, 0x40, 0x04, 0xc8, 0xb2, 0xe0, 0x92, 0x8d, 0x33,
	0x38, 0x9d, 0xb1, 0x00, 0x59, 0x65, 0x2a, 0xc4, 0x77, 0xd1, 0x9a, 0xac, 0xf2, 0x9c, 0x8a, 0xb9,
	0x5f, 0x33, 0xde, 0xfa, 0xa6, 0x2c, 0xc6, 0xad, 0x91, 0x0d, 0x93, 0x1c, 0xa4, 0xa4, 0x53, 0x08,
	0x71, 0x17, 0x35, 0x8c, 0x98, 0x98, 0xf1, 0x14, 0x4e, 0xfc, 0x55, 0xe2, 0xb5, 0x57, 0xa3, 0x7b,
	0x26, 0x7d, 0x13, 0x7f, 0x34, 0xa8, 0xf2, 0x31, 0x2c, 0x19, 0x58, 0xd5, 0x63, 0x60, 0x7c, 0x7a,
	0x2a, 0x37, 0xc4, 0x3b, 0x08, 0xd9, 0x12, 0x92, 0xbd, 0x02, 0xff, 0xaa, 0xa9, 0xf0, 0xa9, 0xa9,
	0xf0, 0x31, 0xbe, 0x3d, 0x62, 0xaf, 0xe0, 0x75, 0xbc, 0xfa, 0x6f, 0x81, 0x80, 0xa0, 0x6b, 0xce,
	0xad, 0x06, 0x5a, 0x0c, 0xbd, 0x75, 0x05, 0xd7, 0xd1, 0xd5, 0xfe, 0x70, 0x78, 0x38, 0x6c, 0x79,
	0xc1, 0x2f, 0x35, 0x74, 0xeb, 0xec, 0xc4, 0x9e, 0x83, 0x60, 0x13, 0x96, 0x50, 0xc5, 0x0a, 0x3e,
	0x34, 0xa2, 0xf1, 0x00, 0xd5, 0xdd, 0xb4, 0x59, 0xea, 0x36, 0xfa, 0xb1, 0x21, 0xf1, 0x10, 0x3f,
	0x18, 0x29, 0xa1, 0x5b, 0xb2, 0x14, 0xb8, 0x62, 0x93, 0xb9, 0x7e, 0x3f, 0x3f, 0x51, 0xab, 0x2b,
	0x99, 0x41, 0xf2, 0x83, 0x56, 0xf5, 0xe2, 0x22, 0xf7, 0x56, 0x2e, 0x77, 0xef, 0x91, 0x69, 0xd8,
	0xc1, 0xe1, 0x79, 0xf7, 0x5c, 0x13, 0x35, 0xa3, 0xea, 0x8e, 0x7c, 0xbd, 0xd7, 0xa3, 0xe5, 0x92,
	0xd6, 0xcc, 0x92, 0x6e, 0x86, 0x97, 0x8b, 0x75, 0x1b, 0x8a, 0xaf, 0xa3, 0xa6, 0xc5, 0xc5, 0xce,
	0x4f, 0xe3, 0x5f, 0x1d, 0xef, 0xa0, 0xba, 0x62, 0x39, 0x48, 0x45, 0xf3, 0xd2, 0x19, 0xe2, 0x2c,
	0x45, 0x8d, 0x61, 0x6f, 0xaf, 0x47, 0x15, 0xe8, 0xef, 0xf8, 0xc6, 0xd1, 0x22, 0x6b, 0x41, 0xd3,
	0x50, 0x0a, 0x83, 0x2f, 0x97, 0x8e, 0xac, 0xa1, 0xda, 0x20, 0xee, 0xb6, 0xae, 0x9c, 0xb5, 0xc6,
	0xd3, 0x87, 0xe3, 0xee, 0x70, 0xb0, 0x3f, 0x78, 0xd2, 0x5a, 0xd1, 0x87, 0xbd, 0xee, 0xfe, 0xc1,
	0xb3, 0x61, 0xbf, 0x55, 0x0b, 0x8e, 0xd1, 0xed, 0xcb, 0xb9, 0xcb, 0x03, 0x26, 0x15, 0xee, 0xa0,
	0x35, 0xbb, 0xac, 0xfa, 0xbf, 0xac, 0xb5, 0x1b, 0x5b, 0x1f, 0xbc, 0x41, 0x72, 0xf0, 0xb3, 0x87,
	0xde, 0xeb, 0xe7, 0x94, 0x65, 0x67, 0xf3, 0xf4, 0x6d, 0x80, 0x13, 0xf4, 0x36, 0xe8, 0x0f, 0x31,
	0x4d, 0x53, 0x01, 0x52, 0x3a, 0xf7, 0x0f, 0x8c, 0xe2, 0x3d, 0x84, 0x7b, 0x45, 0x4e, 0x19, 0x37,
	0xd8, 0xae, 0xcd, 0xc0, 0x1d, 0x7d, 0x4b, 0x19, 0x10, 0x71, 0x20, 0xe3, 0xcc, 0xe2, 0xb7, 0x90,
	0xe4, 0x47, 0x96, 0x65, 0xfa, 0x96, 0x92, 0xc0, 0x15, 0x51, 0x45, 0x88, 0x6f, 0xa2, 0x75, 0x93,
	0x2f, 0xe3, 0x8c, 0xe5, 0x4c, 0x99, 0x4d, 0x58, 0xdd, 0xae, 0x7d, 0xde, 0xe9, 0x04, 0xbf, 0x79,
	0xc8, 0x8f, 0xd8, 0xf4, 0xbb, 0x0a, 0xc4, 0xfc, 0x1c, 0xb9, 0x2e, 0x6a, 0xda, 0x5b, 0x3a, 0x2e,
	0x4a, 0xad, 0x46, 0xba, 0x1d, 0x6a, 0x86, 0x7d, 0x13, 0x3e, 0xb4, 0xd1, 0xe8, 0xa6, 0x61, 0xbb,
	0x81, 0xdf, 0xb1, 0x61, 0xe2, 0xb2, 0x43, 0xdf, 0xc3, 0xdf, 0xa3, 0x66, 0x52, 0xf0, 0x97, 0x20,
	0x54, 0xfc, 0x92, 0x66, 0x15, 0xd8, 0x2d, 0x79, 0x6b, 0x7b, 0x55, 0x89, 0x0a, 0xa2, 0xaf, 0x0d,
	0xf0, 0x0b, 0xfc, 0x60, 0x7f, 0x42, 0x74, 0xe0, 0x1e, 0x71, 0xc9, 0xc4, 0x26, 0x9b, 0xdb, 0xc1,
	0x52, 0xb8, 0x3f, 0x11, 0x0c, 0x78, 0x9a, 0xcd, 0x75, 0x2c, 0xa7, 0x2a, 0xf4, 0x57, 0x82, 0x5f,
	0x3d, 0xb4, 0xb1, 0x3b, 0x7a, 0xfe, 0x7f, 0xe3, 0xfd, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x25,
	0xdc, 0x6b, 0x61, 0x11, 0x07, 0x00, 0x00,
}
