// This file has been autogenerated by ./generate/gen-functions.sh

package apiclient

func (c APIClient) RemoveClientsLabels(rq ApiRemoveClientsLabelsArgs) error {
	return c.post("/api/clients/labels/remove", &rq)
}
