// This file has been autogenerated by ./generate/gen-functions.sh

package apiclient

func (c APIClient) SearchClients(rq ApiSearchClientsArgs) (rs *ApiSearchClientsResult, err error) {
	rs = new(ApiSearchClientsResult)
	if err := c.do("GET", "/api/clients", &rq, rs); err != nil {
		return nil, err
	}
	return
}
