// This file has been autogenerated by ./generate/gen-functions.sh

package apiclient

func (c APIClient) UploadArtifact(rq ApiUploadArtifactArgs) error {
	return c.post("/api/artifacts/upload", &rq)
}
