#!/bin/sh

set -eu

funcname=$1
method=$2
path=$3
filename=$(echo $funcname | tr 'A-Z' 'a-z')

case "$method" in
    get|post)		  
	cat <<EOF > $filename.go
// This file has been autogenerated by $0

package apiclient

func (c APIClient) ${funcname}(rq Api${funcname}Args) (rs *Api${funcname}Result, err error) {
	rs = new(Api${funcname}Result)
	if err := c.do("GET", "${path}", &rq, rs); err != nil {
		return nil, err
	}
	return
}
EOF
	;;
    get-simple)
	cat <<EOF > $filename.go
// This file has been autogenerated by $0

package apiclient

func (c APIClient) ${funcname}() (rs *Api${funcname}Result, err error) {
	rs = new(Api${funcname}Result)
	if err := c.get("${path}", nil, rs); err != nil {
		return nil, err
	}
	return
}
EOF
	;;
    post-simple)
	cat <<EOF > $filename.go
// This file has been autogenerated by $0

package apiclient

func (c APIClient) ${funcname}(rq Api${funcname}Args) error {
	return c.post("${path}", &rq)
}
EOF
	;;
    *)
	echo "unknown method $method" >&2; exit 1
	;;
esac
